package com.ratkko.spongebob.events;

import org.bukkit.Material;

public class getBlock {

    public static Material get_block(String get_block) {
        switch (get_block) {
            case "bone_block":
                return Material.BONE_BLOCK;
            case "bookshelf":
                return Material.BOOKSHELF;
            case "bricks":
                return Material.BRICKS;
            case "clay":
                return Material.CLAY;
            case "coal_block":
                return Material.COAL_BLOCK;
            case "coal_ore":
                return Material.COAL_ORE;
            case "coarse_dirt":
                return Material.COARSE_DIRT;
            case "cobblestone":
                return Material.COBBLESTONE;
            case "mossy_cobblestone":
                return Material.MOSSY_COBBLESTONE;
            case "black_concrete":
                return Material.BLACK_CONCRETE;
            case "blue_concrete":
                return Material.BLUE_CONCRETE;
            case "brown_concrete":
                return Material.BROWN_CONCRETE;
            case "cyan_concrete":
                return Material.CYAN_CONCRETE;
            case "gray_concrete":
                return Material.GRAY_CONCRETE;
            case "green_concrete":
                return Material.GREEN_CONCRETE;
            case "light_blue_concrete":
                return Material.LIGHT_BLUE_CONCRETE;
            case "lime_concrete":
                return Material.LIME_CONCRETE;
            case "magenta_concrete":
                return Material.MAGENTA_CONCRETE;
            case "orange_concrete":
                return Material.ORANGE_CONCRETE;
            case "pink_concrete":
                return Material.PINK_CONCRETE;
            case "purple_concrete":
                return Material.PURPLE_CONCRETE;
            case "red_concrete":
                return Material.RED_CONCRETE;
            case "white_concrete":
                return Material.WHITE_CONCRETE;
            case "yellow_concrete":
                return Material.YELLOW_CONCRETE;
            case "diamond_block":
                return Material.DIAMOND_BLOCK;
            case "diamond_ore":
                return Material.DIAMOND_ORE;
            case "dirt":
                return Material.DIRT;
            case "emerald_block":
                return Material.EMERALD_BLOCK;
            case "emerald_ore":
                return Material.EMERALD_ORE;
            case "end_stone_bricks":
                return Material.END_STONE_BRICKS;
            case "end_stone":
                return Material.END_STONE;
            case "black_glazed_terracotta":
                return Material.BLACK_GLAZED_TERRACOTTA;
            case "blue_glazed_terracotta":
                return Material.BLUE_GLAZED_TERRACOTTA;
            case "brown_glazed_terracotta":
                return Material.BROWN_GLAZED_TERRACOTTA;
            case "cyan_glazed_terracotta":
                return Material.CYAN_GLAZED_TERRACOTTA;
            case "gray_glazed_terracotta":
                return Material.GRAY_GLAZED_TERRACOTTA;
            case "green_glazed_terracotta":
                return Material.GREEN_GLAZED_TERRACOTTA;
            case "light_blue_glazed_terracotta":
                return Material.LIGHT_BLUE_GLAZED_TERRACOTTA;
            case "lime_glazed_terracotta":
                return Material.LIME_GLAZED_TERRACOTTA;
            case "magenta_glazed_terracotta":
                return Material.MAGENTA_GLAZED_TERRACOTTA;
            case "orange_glazed_terracotta":
                return Material.ORANGE_GLAZED_TERRACOTTA;
            case "pink_glazed_terracotta":
                return Material.PINK_GLAZED_TERRACOTTA;
            case "purple_glazed_terracotta":
                return Material.PURPLE_GLAZED_TERRACOTTA;
            case "red_glazed_terracotta":
                return Material.RED_GLAZED_TERRACOTTA;
            case "white_glazed_terracotta":
                return Material.WHITE_GLAZED_TERRACOTTA;
            case "yellow_glazed_terracotta":
                return Material.YELLOW_GLAZED_TERRACOTTA;
            case "glowstone":
                return Material.GLOWSTONE;
            case "gold_block":
                return Material.GOLD_BLOCK;
            case "gold_ore":
                return Material.GOLD_ORE;
            case "ice":
                return Material.ICE;
            case "packed_ice":
                return Material.PACKED_ICE;
            case "iron_block":
                return Material.IRON_BLOCK;
            case "iron_ore":
                return Material.IRON_ORE;
            case "lapis_block":
                return Material.LAPIS_BLOCK;
            case "lapis_ore":
                return Material.LAPIS_ORE;
            case "acacia_wood":
                return Material.ACACIA_WOOD;
            case "dark_oak_wood":
                return Material.DARK_OAK_WOOD;
            case "birch_wood":
                return Material.BIRCH_WOOD;
            case "jungle_wood":
                return Material.JUNGLE_WOOD;
            case "oak_wood":
                return Material.OAK_WOOD;
            case "spruce_wood":
                return Material.SPRUCE_WOOD;
            case "melon":
                return Material.MELON;
            case "mycelium":
                return Material.MYCELIUM;
            case "netherrack":
                return Material.NETHERRACK;
            case "note_block":
                return Material.NOTE_BLOCK;
            case "obsidian":
                return Material.OBSIDIAN;
            case "acacia_planks":
                return Material.ACACIA_PLANKS;
            case "dark_oak_planks":
                return Material.DARK_OAK_PLANKS;
            case "birch_planks":
                return Material.BIRCH_PLANKS;
            case "jungle_planks":
                return Material.JUNGLE_PLANKS;
            case "oak_planks":
                return Material.OAK_PLANKS;
            case "spruce_planks":
                return Material.SPRUCE_PLANKS;
            case "quartz_block":
                return Material.QUARTZ_BLOCK;
            case "nether_quartz_ore":
                return Material.NETHER_QUARTZ_ORE;
            case "redstone_block":
                return Material.REDSTONE_BLOCK;
            case "redstone_lamp":
                return Material.REDSTONE_LAMP;
            case "redstone_ore":
                return Material.REDSTONE_ORE;
            case "sandstone":
                return Material.SANDSTONE;
            case "soul_sand":
                return Material.SOUL_SAND;
            case "stone":
                return Material.STONE;
            case "mossy_stone_bricks":
                return Material.MOSSY_STONE_BRICKS;
            case "andesite":
                return Material.ANDESITE;
            case "polished_andesite":
                return Material.POLISHED_ANDESITE;
            case "diorite":
                return Material.DIORITE;
            case "polished_diorite":
                return Material.POLISHED_DIORITE;
            case "granite":
                return Material.GRANITE;
            case "polished_granite":
                return Material.POLISHED_GRANITE;
            case "black_wool":
                return Material.BLACK_WOOL;
            case "blue_wool":
                return Material.BLUE_WOOL;
            case "brown_wool":
                return Material.BROWN_WOOL;
            case "cyan_wool":
                return Material.CYAN_WOOL;
            case "gray_wool":
                return Material.GRAY_WOOL;
            case "green_wool":
                return Material.GREEN_WOOL;
            case "light_blue_wool":
                return Material.LIGHT_BLUE_WOOL;
            case "lime_wool":
                return Material.LIME_WOOL;
            case "magenta_wool":
                return Material.MAGENTA_WOOL;
            case "orange_wool":
                return Material.ORANGE_WOOL;
            case "pink_wool":
                return Material.PINK_WOOL;
            case "purple_wool":
                return Material.PURPLE_WOOL;
            case "red_wool":
                return Material.RED_WOOL;
            case "white_wool":
                return Material.WHITE_WOOL;
            case "yellow_wool":
                return Material.YELLOW_WOOL;
        }

        return null;
    }

}